# Site settings
title: Temesghen Kahsai
tagline: '&#4720&#4632&#4661&#4872&#4757'
email: lememta@gmail.com
description: 'Personal site of Teme'
baseurl: ""
url: "http://lememta.github.io/"

author:
  name:           'Temesghen Kahsai'
  url:            http://lememta.github.io/

# Build settings
markdown: kramdown
permalink: pretty

paginate:         5

gems:
  - jekyll-sitemap
